package lexical;

public enum Tokens {
	IDENTIFIER, I_CONSTANT, F_CONSTANT, STRING_LITERAL, FUNC_NAME, SIZEOF,
	PTR_OP, INC_OP, DEC_OP, LEFT_OP, RIGHT_OP, LE_OP, GE_OP, EQ_OP, NE_OP,
	AND_OP, OR_OP, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN, ADD_ASSIGN,
	SUB_ASSIGN, LEFT_ASSIGN, RIGHT_ASSIGN, AND_ASSIGN,
	XOR_ASSIGN, OR_ASSIGN,
	TYPEDEF_NAME, ENUMERATION_CONSTANT,
	
	TYPEDEF, EXTERN, STATIC, AUTO, REGISTER, INLINE,
	CONST, RESTRICT, VOLATILE,
	
	BOOL, CHAR, SHORT, INT, LONG, SIGNED, UNSIGNED, FLOAT, DOUBLE, VOID,
	COMPLEX, IMAGINARY,
	STRUCT, UNION, ENUM, ELLIPSIS,
	
	CASE, DEFAULT, IF, ELSE, SWITCH, WHILE, DO, FOR, GOTO, CONTINUE, BREAK, RETURN,

	ALIGNAS, ALIGNOF, ATOMIC, GENERIC, NORETURN, STATIC_ASSERT, THREAD,_LOCAL,
	
	COMMA, COLON, LBRACE, RBRACE, LPAREN, RPAREN, LBRACK, RBRACK, DOT, AND, NOT,
	COMP, PLUS, MINUS, DIV, MULT, MOD, LT, GT, XOR, OR, QUESTION, EQ, SEMICOLON
	
	;
}
